apiVersion: agent.kagenti.dev/v1alpha1
kind: AgentBuild
metadata:
  name: helloworld-agent-build
  namespace: kagenti
spec:
  mode: dev
  source:
    sourceRepository: "github.com/a2aproject/a2a-samples.git"
    sourceRevision: "main"
    sourceSubfolder: "samples/python/agents/helloworld"
    sourceCredentials:
      name: github-token-secret

  pipeline:
    namespace: kagenti-system
    parameters:
    - name: SOURCE_REPO_SECRET
      value: github-token-secret
    - name: START_COMMAND          # Custom start command
      value: "python __main__.py"
    - name: PYTHON_VERSION         # Specify Python version
      value: "3.13"
  buildOutput:
    image: "helloworld-service"
    imageTag: "v0.0.1"
    imageRegistry: "registry.cr-system.svc.cluster.local:5000"
    imageRepoCredentials:
      name: ghcr-secret

---
apiVersion: agent.kagenti.dev/v1alpha1
kind: Agent
metadata:
  name: helloworld-agent
  namespace: kagenti
  labels:
    app: helloworld-service

  annotations:
    description: "helloworld agent"
spec:
  description: "Agent saying Hello"

  replicas: 1

  # Use existing container image
  imageSource:
    buildRef:
      name: helloworld-agent-build

  # Define service ports to expose
  servicePorts:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000

  # Complete pod template specification
  podTemplateSpec:
    spec:
      containers:
      - name: agent # use fixed name "agent" for the main container
        image: "registry.cr-system.svc.cluster.local:5000/helloworld-service:v0.0.1"

        # Environment variables
        env:
        - name: PORT
          value: "8000"
        - name: HOST
          value: 0.0.0.0
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector.kagenti-system.svc.cluster.local:8335
        - name: KEYCLOAK_URL
          value: http://keycloak.keycloak.svc.cluster.local:8080
        - name: UV_CACHE_DIR
          value: /app/.cache/uv
        - name: LLM_API_BASE
          value: http://host.docker.internal:11434/v1
        - name: LLM_API_KEY
          value: dummy
        - name: LLM_MODEL
          value: llama3.2:3b-instruct-fp16
        - name: MCP_URL
          value: http://weather-tool:8000/mcp
        - name: GITHUB_SECRET_NAME
          value: github-token-secret
        - name: CLIENT_NAME
          value: kagenti/weather-service
        - name: CLIENT_ID
          value: spiffe://localtest.me/sa/weather-service
        - name: NAMESPACE
          value: kagenti
