/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	"context"
	"encoding/json"
	"net/http"
	"strings"

	"github.com/kagenti/operator/internal/webhook/injector"
	corev1 "k8s.io/api/core/v1"
	ctrl "sigs.k8s.io/controller-runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
)

// authbridgelog is for logging in this package.
var authbridgelog = logf.Log.WithName("authbridge-webhook")

// AuthBridgeWebhook handles mutation of Pod resources for AuthBridge injection
type AuthBridgeWebhook struct {
	Mutator *injector.PodMutator
	decoder admission.Decoder
}

// SetupAuthBridgeWebhookWithManager registers the authbridge webhook with the manager
func SetupAuthBridgeWebhookWithManager(mgr ctrl.Manager, mutator *injector.PodMutator) error {
	webhook := &AuthBridgeWebhook{
		Mutator: mutator,
		decoder: admission.NewDecoder(mgr.GetScheme()),
	}

	mgr.GetWebhookServer().Register("/mutate-workloads-authbridge", &admission.Webhook{
		Handler: webhook,
	})

	return nil
}

// Handle processes admission requests for Pod resources
//
//nolint:gocritic // hugeParam: admission.Handler interface requires value receiver for admission.Request
func (w *AuthBridgeWebhook) Handle(ctx context.Context, req admission.Request) admission.Response {
	authbridgelog.Info("AuthBridge webhook called",
		"kind", req.Kind.Kind,
		"namespace", req.Namespace,
		"name", req.Name,
		"operation", req.Operation)

	// Only handle Pod resources; allow anything else through unchanged.
	// This guards against transient misconfigurations where the
	// MutatingWebhookConfiguration still targets non-Pod resources.
	if req.Kind.Kind != "Pod" || req.Kind.Group != "" {
		authbridgelog.Info("Skipping non-Pod resource",
			"kind", req.Kind.Kind,
			"group", req.Kind.Group)
		return admission.Allowed("not a Pod")
	}

	var pod corev1.Pod
	if err := w.decoder.Decode(req, &pod); err != nil {
		authbridgelog.Error(err, "Failed to decode Pod")
		return admission.Errored(http.StatusBadRequest, err)
	}

	// Derive a workload name for ServiceAccount and client-registration naming.
	// At Pod CREATE time the Name may be empty (generated by the API server),
	// but GenerateName is set by the owning controller (e.g. "myapp-7d4f8b9c5-").
	resourceName := deriveWorkloadName(&pod)

	// Check if already injected (idempotency)
	if w.isAlreadyInjected(&pod.Spec) {
		authbridgelog.Info("Skipping - sidecars already injected",
			"namespace", req.Namespace,
			"name", resourceName)
		return admission.Allowed("already injected")
	}

	if mutated, err := w.Mutator.InjectAuthBridge(ctx, &pod.Spec, req.Namespace, resourceName, pod.Labels, pod.Annotations); err != nil {
		authbridgelog.Error(err, "Failed to mutate pod spec",
			"namespace", req.Namespace,
			"name", resourceName)
		return admission.Errored(http.StatusInternalServerError, err)
	} else if !mutated {
		authbridgelog.Info("Skipping mutation (injection not enabled)",
			"namespace", req.Namespace,
			"name", resourceName)
		return admission.Allowed("injection not enabled")
	}

	// Marshal the mutated Pod
	marshaledMutated, err := json.Marshal(&pod)
	if err != nil {
		authbridgelog.Error(err, "Failed to marshal mutated Pod")
		return admission.Errored(http.StatusInternalServerError, err)
	}

	authbridgelog.Info("Successfully mutated Pod",
		"namespace", req.Namespace,
		"name", resourceName)

	return admission.PatchResponseFromRaw(req.Object.Raw, marshaledMutated)
}

// deriveWorkloadName extracts a workload name from the Pod for ServiceAccount
// and client-registration naming. For controller-managed Pods, GenerateName
// is set (e.g. "myapp-7d4f8b9c5-") and we trim the trailing hyphen — this
// yields the ReplicaSet name (e.g. "myapp-7d4f8b9c5"), not the Deployment
// name. Resolving the Deployment name requires a ReplicaSet owner-ref lookup,
// which is planned for Phase 2 (AgentRuntime CR integration, issue #177).
// For bare Pods, we use the Pod name directly.
func deriveWorkloadName(pod *corev1.Pod) string {
	if pod.GenerateName != "" {
		return strings.TrimRight(pod.GenerateName, "-")
	}
	if pod.Name != "" {
		return pod.Name
	}
	// Both GenerateName and Name empty — should not happen for valid
	// admission requests, but fall back to UID to avoid empty names.
	authbridgelog.V(0).Info("Pod has neither Name nor GenerateName, falling back to UID",
		"uid", pod.UID)
	return string(pod.UID)
}

func (w *AuthBridgeWebhook) isAlreadyInjected(podSpec *corev1.PodSpec) bool {
	// Check sidecar containers. Any one of these being present means the full
	// injection cycle already ran for this pod (each Build* call is guarded by
	// containerExists/volumeExists checks for idempotency).
	for i := range podSpec.Containers {
		if podSpec.Containers[i].Name == injector.EnvoyProxyContainerName ||
			podSpec.Containers[i].Name == injector.SpiffeHelperContainerName ||
			podSpec.Containers[i].Name == injector.ClientRegistrationContainerName ||
			podSpec.Containers[i].Name == injector.AuthBridgeContainerName {
			return true
		}
	}
	// Also check init containers — proxy-init is always injected by InjectAuthBridge
	for i := range podSpec.InitContainers {
		if podSpec.InitContainers[i].Name == injector.ProxyInitContainerName {
			return true
		}
	}
	return false
}

// +kubebuilder:webhook:path=/mutate-workloads-authbridge,mutating=true,failurePolicy=fail,sideEffects=None,groups="",resources=pods,verbs=create,versions=v1,name=inject.kagenti.io,admissionReviewVersions=v1,reinvocationPolicy=IfNeeded
